name: Deploy to Netlify

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:
    inputs:
      deploy-msg:
        description: 'Deploy Message (visible in Netlify)'
        required: true

jobs:
  deploy:
    name: Build and Deploy to Netlify
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          deploy-message: "Deploy from GitHub Actions: ${{ github.event.inputs.deploy-msg }}"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
