name: Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run codebase:lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Run integration tests
        run: npm run cypress

      - name: Merge code coverage reports
        run: npm run test:merge-coverage

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
