name: Publish packages to npmjs

on:
  push:
    branches:
      - chore/106-add-publish-workflow-for-monorepo
  # release:
  #   types:
  #     - published

jobs:
  publish:
    name: Publish packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish packages to npmjs
        run: npx lerna publish from-package --yes
