name: CLI Test

on: push

jobs:
  test:
    name: Run CLI test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "packages/cli-tool"
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: NPM install and run tests
        run: |
          npm ci
          npm test
